### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by arnav56745** [billyeatcookies/Biscuit#106]
## Bug
> Describe the bug

When starting biscuit I get this error
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ramit Katyal\git\Biscuit\biscuit\__main__.py", line 17, in <module>
    from biscuit.app import App
ModuleNotFoundError: No module named 'biscuit'
```

https://github.com/billyeatcookies/Biscuit/assets/96387132/cef4ca01-34ea-4500-b6ce-4f3262e1411a

(i have custom powershell prompt dont mind it)
By the way I already have the libraries installed
### System Information
- OS: Windows 10
- Python Version: 3.11

**Comment by billyeatcookies** [comment]
@arnav56745 sorry for the delay! (uni)

you need to run with `-m` flag as a module. see the README for running and compiling!

**Comment by arnav56745** [comment]
@billyeatcookies  in the previous readme it said to 
```
$ python biscuit
```
thats why i got this error
