### ISSUE TITLE
I Never See A IDE Like This

### ISSUE THREAD

**Issue by ltaoist** [billyeatcookies/Biscuit#109]
This is sooooooooooo awesome ! This editor has a soooooooooooo awesome and clear outlook, it just build start tk but it really like a 21st Century .

And I look inside the source code, it implement sooooooooo awesome and clear structure too. I can't stop myself that is the universal best IDE Biscuit !

**Comment by billyeatcookies** [comment]
Heyy @ltaoist, thanks alot for the review! ❤

Really glad that you liked the project. If you are thinking about contributing any ideas definitely do so, always looking forward to receiving ideas!
