### ISSUE TITLE
Palette File Search is not showing all files in entire project

### ISSUE THREAD

**Issue by billyeatcookies** [billyeatcookies/biscuit#111]
## Bug
Since we are not loading directory items in tree recursively as a whole anymore (to save memory), the current mechanism of collecting files from `create_root` wont work as expected. This will make the file search of palette fail as a result.

see: https://github.com/billyeatcookies/Biscuit/blob/a4f19eafb88832cf18535d3aa2e6f22d6948eefe/biscuit/core/components/views/sidebar/explorer/directorytree.py#L81-L85

- Need a better way of collecting all files in directory opened and all of its child directories

**Comment by KristoferSoler** [comment]
Hi @billyeatcookies,

I could take this issue if you want. If am not wrong what we want here is to list all the files from the current project/folder, right?

**Comment by billyeatcookies** [comment]
@KristoferSoler the floating palette component uses Actionsets (contains id, prefix, items, pinned items) for distinguishing command groups. So the explorer provides and updates the file search actionset. 

When new directory is opened, the actionset is updated too. But in a recent change, the explorer directory tree was altered to work in a multithreaded lazy loading way, by only loading sub directories when that node is toggled in tree. Before it used to recursively load all sub directories and all files within active directory when its opened, which i thought would be unnecessary. But this affected the updation of file search actionset, **the actionset would only show results for latest toggled node in the tree**.

Task left here now is that the actionset updation should be done in `change_path`

- directory tree: https://github.com/billyeatcookies/Biscuit/blob/a4f19eafb88832cf18535d3aa2e6f22d6948eefe/biscuit/core/components/views/sidebar/explorer/directorytree.py

**Comment by KristoferSoler** [comment]
So, if I understand correctly the issue here is that the palette is not updating the commands when you toggle a new folder.
And we want to update the palette commands each time we toggle a folder on the tree view.

Am I right?

**Comment by billyeatcookies** [comment]
The file search actionset of palette is special. The commands are file names, when we run commands the file will be opened in editor. The file search shall show results for all the sub directories within the opened directories too.

Before the change, file tree used to load all the subdirectories of opened directory recursively, and while doing this we also collect the commands for palette! So both jobs done efficiently. But, after the recent change, file tree doesn't load all directory items recursively; instead just loads what's in the current directory, and then load items for whichever node is toggled (that saves memory alot). But then the file search command loading process fails to work properly.

- So we need to separately do the file search command updating upon [active directory change](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/components/views/sidebar/explorer/directorytree.py#L55) in the editor. After the loading of directory tree items, preferably. 
- Updating the actionset is simple, just reassign a new instance
```py
self.actionset = ActionSet("Search files by name", "file:", self.files)
```

- currently [commands are updated here](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/components/views/sidebar/explorer/directorytree.py#L86C31-L86C31)
