### ISSUE TITLE
How do you implement games in this

### ISSUE THREAD

**Issue by arnav56745** [billyeatcookies/Biscuit#113]
How do you implement games in this? its so complex

**Comment by billyeatcookies** [comment]
@arnav56745 Only the game logic is the complication here, rest are all pretty simply done.

- every game class inherits from [BaseGame](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/components/games/game.py).
- games are added to Palette by registering them [here](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/components/games/__init__.py#L14)
- further to use widgets used across the editor, import from `biscuit.core.components.utils` module

see the simple [tic tac toe implementation](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/components/games/ttt.py)
