### ISSUE TITLE
Shall there be a Big Picture for Biscuit？

### ISSUE THREAD

**Issue by ltaoist** [billyeatcookies/Biscuit#121]
A picture describe how Biscuit integrate and promote the current market editor idea？

**Comment by ltaoist** [comment]
A picture describe how Biscuit integrate and promote the current market editor idea？

**Comment by billyeatcookies** [comment]
Hey there @ltaoist , thanks for the suggestion! 
I liked the idea of having a picture to show the integration of biscuit extensions etc. 

Also i have been documenting the codebasw properly lately so thats why commits are missing (unrelated but im also busy with university)

**Comment by ltaoist** [comment]
Supersonic! I like you word that "a picture to extensions”. I think this would help to a clean design.

Instance That Extensions Category Paradigm
=============================

As as instance, emacs wiki show a ["CategoryExtensions"](https://www.emacswiki.org/emacs/CategoryExtensions):

![EWI](https://github.com/billyeatcookies/Biscuit/assets/1416332/13662d02-781b-4c91-af46-cb7a0ac5e605)

Further more, I don't know if it important how [python](https://pypi.org/search/) do category for its package, but I try to list it:

![PY](https://github.com/billyeatcookies/Biscuit/assets/1416332/af0f8f69-f1f6-40db-b0be-a75c6a04218a)

And as [visual studio](https://marketplace.visualstudio.com/search?target=VS&category=All%20categories&vsVersion=vs2022&sortBy=Installs), it split into "controls, templates, tools" :

![VS](https://github.com/billyeatcookies/Biscuit/assets/1416332/518611a2-c771-4cc8-8f2b-878abaad57e1)

And for [vs code](https://marketplace.visualstudio.com/search?target=VSCode&category=All%20categories&sortBy=Installs):

![VSCode](https://github.com/billyeatcookies/Biscuit/assets/1416332/6607d7cd-a8c8-44dd-99ed-34c7547c30bc)

Views On Programming Environment
=========================

Normally, we may both agree that a computer system made up in five part: input, output, storage, controller, arithmetic. As required for programming , it may program(in human act practice) with,  historically, compiler, interpreter or debugger for least.

And in vs, it is also some profit facility.

Nowadays, thus things are commonly consider as “unliberated necessary”: code completion, code refactor, project management system, code version control, visualized graph construct, efficient intercommunication, development portable support.

I dont really interest on thus above. I think it's painful and difficult to hand up. It is a reflection to fragmentization of MVC-industry.

I used to program in emacs, I use it's buffer, mini-buffer, key-binding, some partial buffer like message echo, process manager and file manager, init.el, hook and theme system, and write some private extendsion. And I think it block my brain -- I lost the imagination beyond "buffer", so I quit emacs now.

And I fall into Kate. It not block me into "buffer", but I also feel a long-time inanity that what a Technical Production is in need. I don't like "network architecture". It bring complex and mind maze.

VS 2022 is good; if a boss lead you and you in duty program a work for he!

My Personal Preference
=================

At the bottom layer, I think it only two key technology : graphic programming and high performance computation. The think linking up the module is our _Mind_, or _Logic_.

**It is radically important developer can product what has potency embedding into the social-developer-user-story-money cycle.**

My Personal Preference is divide work into six kind:

1. Civil Servant Editing -- May overlap to the office suit
2. Editing Keystone -- The infrastructure for a goal, a format, a principle or things helping the social-developer-user-story-money cycle
3. Digital Content Develop -- Nowadays, AI and AIGC and graphic engage into develop in a initiative and intuitional way,
4. AI -- Not only generation, but also goal-archive
5. House Automation -- Make a two-way linking between computer and life style and life quality. 
6. Other

It may too many noise and work load; I have no idea the balance for clearance, typical and preference; Scary!

And More
=======

Actually I only deeply consider the social-developer-user-story-money cycle is important. I got my bachelor's degree 8 year. I deeply seek that if you don't want work for the hypecompany and get zero wages in open source, if there a good way construct the social-developer-user-story-money cycle is important.

I write more, not for I know more, but for I complete lost.

Good Luck!

**Comment by billyeatcookies** [comment]
So the main idea is to have categories for the extensions, am I right? I think you are using a translator, so that's why some parts of the comments are unclear to me. That is also a really good suggestion. We can make this possible with the help of introducing tags to the extensions list. But first of all, the list shall be able to show "author info" and "description of extension" in the GUI first.

This is a really good suggestion

**Comment by ltaoist** [comment]
Thanks your approval. Should there be some “key categories” and how to connect across Biscuit, extensions and categories?

(Sorry for the obscure in my word. I don't using a translator; I not well enough in English……

**Comment by billyeatcookies** [comment]
Actually the idea is still a bit unclear, can you elaborate more. If I'm right the issue is about adding categories to extension store

**Comment by ltaoist** [comment]
I can't. Actually I am bad in make a “classic” design. If we can not prompt something more about this topic, let's stop on "adding categories to extension store", and wait for next muse coming; may not be bad!~

In other hand, if just a temporary sight about connecting across Biscuit, extensions and categories; may a solution, I can try it.

**Comment by billyeatcookies** [comment]
Sure, but we are having this communication issue here, I'm not able to underatand what exactly you are trying to say. Sorry for that 😄

I'd be glad if you come up with any new idea for biscuit, I'll review it ❤️

**Comment by ltaoist** [comment]
Nice, I close this issue, and may a new one like "Some Design Idea About XXX....".

Thanks! You are a great leader!
