### ISSUE TITLE
Making the global search functional

### ISSUE THREAD

**Issue by billyeatcookies** [billyeatcookies/Biscuit#130]
## Feature
As of now, the global search view in sidebar is not functional, only the frontend part is done. 

It is hard to show good and useful results and also maintain performance for the search at the same time. The search is NOT searching for file names, but the content within all the text files in the entire active directory!

I'd love to receive any suggestions and help regarding this issue, how to maintain the performance and also provide good results analyzing all files? and how to optimize this further, share your thoughts and ideas please! 

also let me know of the useful existing libraries that helps on this process!

**Comment by nfoert** [comment]
I believe PyCharm precaches search data when you open a folder for the first time, and then just rechecks files on save, maybe Biscuit could do the same?

**Comment by billyeatcookies** [comment]
@nfoert that sounds nice but also pretty unsure of how to implement such a system.

as a very basic example, following function prints all the files containing the lookup string also with occurrences
```py
import os

def search(directory, search_string):
    found_files = []
    for root, _, files in os.walk(directory):
        for file in files:
            file_path = os.path.join(root, file)
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
                if search_string in content:
                    found_files.append(file_path)
                    occurrences = content.count(search_string)
                    print(f"Found '{search_string}' in '{file_path}' ({occurrences} times)")

    return found_files

found_files = search("D:\\github\\biscuit", "class")
```

this opens and reads the entire file then looks up for the occurrences, its not that fast.

**Comment by nfoert** [comment]
That is true, I wouldn't know how to extract a string from the precached data anyway.

I modified your code a little bit and did a few tests, on my 12th Gen Intel i7-12700L searching a medium-sized project (including a virtual environment) for "print" took 1.58 seconds. 

Obviously this would depend on the user's computer and the size of the project, but this doesn't feel *that* slow to me.

There would still probably be a better way but I can't really think of any better options... Maybe you could potentially use async or threads in some form (Main thread loads files, another thread searches for occurrences)

Here's the code I used:
```py
import os
import time

start = time.time()
search_string = "print"

found_files = []
for root, _, files in os.walk("."): # Searches current directory for files
    for file in files:
        file_path = os.path.join(root, file)
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
            if search_string in content:
                found_files.append(file_path)
                occurrences = content.count(search_string)
                print(f"Found '{search_string}' in '{file_path}' ({occurrences} times)")

end = time.time()

print(f"Took {end - start} seconds to search")
```

Also I would be willing to try and implement this issue once we find a suitable searching system if you're looking for help.

**Comment by billyeatcookies** [comment]
I guess we can give this a shot as is then! as for the interface part, using a treeview to display the results (more optimized option than adding in bunch of buttons i guess) each file with occurrence will be made a node in tree, and it will show occurrence lines as its children.

- [search view](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/components/views/sidebar/search)
- [utils.tree](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/components/utils/tree.py)

**Comment by nfoert** [comment]
Alright, thanks for pointing me in the right direction! I'll get started on this tomorrow, will have to get accustomed to your repo's organization.

**Comment by cid0rz** [comment]
Hello. You could use a tool like ripgrep, and some python library that uses
it to get search results fast.

Regards

**Comment by billyeatcookies** [comment]
@nfoert you talked about using multithreading to speed up the process, it was a nice suggestion too

```py
import os
import concurrent.futures

def search_in_file(file_path, search_string):
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
        if search_string in content:
            occurrences = content.count(search_string)
            print(f"Found '{search_string}' in '{file_path}' ({occurrences} times)")
            return file_path

def search(directory, search_string):
    found_files = []
    with concurrent.futures.ThreadPoolExecutor() as executor:
        for root, _, files in os.walk(directory):
            for file in files:
                file_path = os.path.join(root, file)
                future = executor.submit(search_in_file, file_path, search_string)
                if future.result():
                    found_files.append(future.result())
    return found_files

found_files = search("D:\\github\\biscuit", "class")
```

running the search and reading parallel saved some time

**Comment by billyeatcookies** [comment]
further I also tried pretty printing the occurrence lines, and also highlighting occurrence
```py
import os
import concurrent.futures

def search_in_file(file_path, search_string):
    found = False
    occurrences = 0
    result_lines = []

    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        for line_number, line in enumerate(f, start=1):
            if search_string in line:
                found = True
                occurrences += line.count(search_string)
                result_lines.append((line_number, line.strip()))

    if found:
        print(f"{file_path} ({occurrences} occurrences):")
        for line_number, line in result_lines:
            print(f"    line {line_number}: {line}")
            print(f"            {' ' * (line.find(search_string))}{'^' * len(search_string)}")

def search(directory, search_string):
    found_files = []
    with concurrent.futures.ThreadPoolExecutor() as executor:
        for root, _, files in os.walk(directory):
            for file in files:
                if file.endswith('.pyc'): continue
                file_path = os.path.join(root, file)
                future = executor.submit(search_in_file, file_path, search_string)
                if future.result():
                    found_files.append(future.result())
    return found_files

found_files = search("D:\\github\\biscuit", "class")
```

**Comment by nfoert** [comment]
Alright, that looks good, thanks for the snippet. I'll give it a try. I'm currently working on installing everything.

**Comment by nfoert** [comment]
Thanks for the reply. I had already installed those packages, and I was still getting the error. I just set up a Windows VM and everything is working perfectly so I should be good to go.

**Comment by nfoert** [comment]
Hi there, I'm having some trouble with the custom `Tree` object. No matter what I do, you can't see the foreground text.
The chevrons display as expected. Using a default `ttk.Treeview` results in the same issue.
Adjusting the font and foreground color in `biscuit/core/settings/styles.py` does not make any difference.
![image](https://github.com/billyeatcookies/Biscuit/assets/92690073/9e0073e6-44e6-4e19-bf86-b72148469cb9)
In `./views/sidebar/search/__init__.py` I'm simply inserting some test values.
```py
        --snip--

        self.treeview = Tree(self)

        parent = self.treeview.insert("", 0, "First Item")
        self.treeview.insert(parent, 0, "Sub Item")

        second_item = self.treeview.insert("", 0, "Second Item")
        self.treeview.insert(second_item, 0, "Second Sub-Item")
        self.treeview.pack(fill=BOTH, expand=True)
        
        self.results = Results(self, **self.base.theme.views.sidebar.item)
        self.results.pack(fill=BOTH, expand=True)
```
Am I doing something wrong here or is this is separate issue?
I'm using a Windows 10 Virtual Machine

**Comment by billyeatcookies** [comment]
@nfoert you will have to explicitly mention `text="first item"`

```py
parent = self.treeview.insert("", 0, text="First Item")
```

**Comment by nfoert** [comment]
@billyeatcookies 
Thanks for the help! I can't believe I missed that in the documentation... 🤦🏾

**Comment by billyeatcookies** [comment]
@nfoert Hey there! any updates on the issue?

**Comment by nfoert** [comment]
Hi, I've not had a ton of time to work on this recently but I have gotten most of it working.
- Search both case sensitive and insensitive
- Display the results in a tree
- Clicking tree items takes you to that file

I do have a strange layout issue that I'm still trying to resolve:
![image](https://github.com/billyeatcookies/Biscuit/assets/92690073/b5226ac7-91e9-42db-993c-3bdd3ed13ab3)

I also need to get asynchronous searching working correctly still, get it to search whole word and regex and I'll probably setup the global replace functionality as well.

Also, have you implemented any way to scroll the editor to a specified line number when using `self.base.open_editor`? I didn't see anything like that but I may be mistaken. Thanks.

**Comment by billyeatcookies** [comment]
@nfoert Looking really great so far! nice progress and thanks alot ❤️ (I'm also busy these days because of uni)

As for the scrolling to line part, yes there is a goto function, which you can access from editor statusbar (click on the line-col info), but yeah didn't implement an open_and_goto function. 

Another thing about the layout, I can help with it if you open the pr now! 

again, thanks for the time you are putting into the feature.
