### ISSUE TITLE
Autosave for editor

### ISSUE THREAD

**Issue by billyeatcookies** [billyeatcookies/Biscuit#134]
## Feature
Biscuit doesn't have autosave feature yet. This is also a very important feature. We can make use of the tkinter `after` method for handling this. Also this autosave will require a field in settings to configure intervals and toggle, maybe also from command palette.

**Comment by KristoferSoler** [comment]
Hi @billyeatcookies , I would like to take this issue. 💪🏽

**Comment by billyeatcookies** [comment]
Hey @KristoferSoler, thanks alot ❤️ 
The autosave can be implemented within the [`TextEditor`](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/components/editors/texteditor/__init__.py) class or [`Editor`](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/components/editors/__init__.py) class, ig former would be better. 

Few things to be noted are that, before calling `editor.save()` the event should be checking:
- `editor.content`
- `editor.content.exists`
- `editor.content.editable`

all these should be satisfied.

**Comment by KristoferSoler** [comment]
Thanks for the info.
I'll start working and make the PR ASAP. :)

**Comment by KristoferSoler** [comment]
> Also, let me know your thoughts on only saving the active tab or saving all the open tabs

I would focus first on the active tab and then watch the performance.
Or even create a new toggle to allow "active tab" o "all tabs". For more options.

**Comment by billyeatcookies** [comment]
@KristoferSoler thanks for the response! ❤️

Regarding the configuration part, #128 mentions about this, since the settings editor isn't fully functional you will have to do this using the config file for now. I will keep the issue updated regarding this. 


- [config loader](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/settings/config/__init__.py)
- [settings.toml](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/config/settings.toml)

**Comment by KristoferSoler** [comment]
Hi @billyeatcookies,

I think we have an issue with `pytest` execution.
```python
for i, item in enumerate(path):
                text = item if item == path[-1] else f"{item} ›"
>               self.additem(os.path.join(*path[:i]), text)
E               TypeError: join() missing 1 required positional argument: 'a'
```

Looking if it was something from my end it seems the array it's build here: https://github.com/billyeatcookies/Biscuit/blob/209945384ae3a16f238f3abd9cada7cc0185e6e1/biscuit/core/components/editors/breadcrumbs/__init__.py#L24

Returns an array with the first element empty, this cause `self.additem(os.path.join(*path[:i]), text)` to break.
At this image you can see the `path` value before and after the treatment.
![image](https://github.com/billyeatcookies/Biscuit/assets/31729650/07ab6995-090f-4207-bb34-6757b909acfa)

I did a search thorough the docs but I couldn't find anything. 
Do I need to configure something I missed?

**Comment by billyeatcookies** [comment]
> Returns an array with the first element empty, this cause self.additem(os.path.join(*path[:i]), text) to break.
@KristoferSoler that's right, there should be checks for non-empty path value. The unit testing part is very much in progress so far, and the tests written so far don't cover the entire editor and it's components.

**Comment by KristoferSoler** [comment]
> > Returns an array with the first element empty, this cause self.additem(os.path.join(*path[:i]), text) to break.
> > @KristoferSoler that's right, there should be checks for non-empty path value. The unit testing part is very much in progress so far, and the tests written so far don't cover the entire editor and it's components.

Roger that. I will overpass this for now and maybe we can work together on this. 💪🏽

**Comment by billyeatcookies** [comment]
@KristoferSoler Thats soo good of you, I'd love to consider that after finishing up on the language server issue!

**Comment by KristoferSoler** [comment]
Hi!

Sorry for the latency. I have been on a trip. I'll create the PR today. :)

**Comment by billyeatcookies** [comment]
It's okay! I'm also busy with uni these days, understandable. 

I'll check and share my thoughts on pr
