### ISSUE TITLE
Add a Text Wrap option to View menu (Menubar)

### ISSUE THREAD

**Issue by billyeatcookies** [billyeatcookies/biscuit#161]
# Feature
Add a word wrap toggle to the View menu in menubar, that would turn on/off the wordwrap globally or for the active editor (which one would be better?)

## Notes
- [View menu](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/layout/menubar/__init__.py#L153): `Menu.add_item(text, callback)` 
- Accessing the [active editor](https://github.com/billyeatcookies/Biscuit/blob/main/CONTRIBUTING.md#the-app-class)

**Comment by tigran2008** [comment]
Personally, I would expect the setting to take effect globally

**Comment by billyeatcookies** [comment]
Yeah, I think that would be more suiting, thanks for the suggestion!

**Comment by billyeatcookies** [comment]
Done!
