### ISSUE TITLE
[Feature request]: Command history navigation in terminal

### ISSUE THREAD

**Issue by arpankumarde** [billyeatcookies/Biscuit#167]
## Feature

When using the terminal in Biscuit, there is no way to navigate through the previous commands using the arrow up and arrow down buttons. This makes it inconvenient for developers to run commands repeatedly or correct typos.

## Expected behavior

In VS Code, the terminal allows users to navigate through the command history using the arrow keys. This is a very useful feature that Biscuit should also support.

## Steps to reproduce

Open the terminal in Biscuit and run some commands. Try to use the arrow keys to go back to the previous commands. Nothing happens.

## Environment

`Biscuit version 2.31.0`, `Windows 10`, `Python 3.12`

## Possible solution

Implement a command history buffer in the terminal class and add key bindings for the arrow keys to access it.

**Comment by billyeatcookies** [comment]
@arpankumarde a really awesome feature request, thanks! ❤️ also please let me know if you'd like to contribute code as well!

## Notes
- A better place to implement this would be the modified text widget class of terminal: https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/components/views/panel/terminal/text.py
- All shell classes are instances of [terminal base class](https://github.com/billyeatcookies/Biscuit/blob/main/biscuit/core/components/views/panel/terminal/terminal.py)

**Comment by arpankumarde** [comment]
Thanks for the appreciation @billyeatcookies 

While I would have loved to contribute to this project, I really do not have the skills to do so. Till I acquire those, I'll keep checking on this project and bring issues to the spotlight.

Happy coding 🚀
