### ISSUE TITLE
Documenting the Extensions API & User Guide

### ISSUE THREAD

**Issue by ltaoist** [billyeatcookies/biscuit#177]
After [a previous issue](https://github.com/billyeatcookies/biscuit/issues/121), and a long reconsidering on "category of extendsion" or "interconnect inside editor components", I cannot find any durable help more. And now I quit that. I think we may restart to a initial part: production base line, what define a editor itself but not another, and I call this as a course named "Capabilities in Editor", and as a periodically conclusion, more specifically, I call this as a course named **"Four Capabilities in Modern Editor"**:

* Capabilities I -- Content Create and Modify Invoking (**CCAMI**). It is important that a modern editor is not just focus in content create and modify , but deeply focus and care in the **_invoking_** of content create and modify. Philosophically, this means that a modern editor take edit as a _act_, but also a _procedure_. **_The duality in edit-as-act and edit-as-procedure_** cause a unimaginable complexity but also a unprecedented performance in a Modern Editor. And as a question, development shall support thus capabilities,  The CCAMI Capabilities, for a substantial editing experience and for a better tomorrow.  There be **_a shift from CCAM paradigm to CCAMI paradigm_** in A modern editor . And both **_text editing_** and **_object editing_** might enter on the stage.
* Capabilities II -- Responsive Editing(**RE**). What you type is what to insert is a most simply policy and a nocturnes in early editor. But nowadays, the ubiquitous connections raise the new _structure_ of Responsive Editing, and more factors may extend, enrich the scope or task of Responsive Editing. We can divide the Responsive Editing in three journey: **_Before-Editing journey_**, **_In-Editing journey_** and **_After-Editing journey_**. But with more generality, there still another some hyper journey: **_Before-Program journey_**, **_In-Program journey_** and **_After-Program journey_** since data or preparation are from hardwards and not just configure files. As a result, development shall support a journey-interesting Responsive Editing.
* Capabilities III -- Working Flow Integration And Progress Governing (**WFIAPG**). The modern life brights tons of inputs, events and interactions into production and individuals, which oppress every worker subjected to his boss, his working flow, but edge out his character. A balance and controllable editor shall both care the **flexibility, reliability and responsibility of individuals**, but also get rid of the inhuman or irrational schooled-flow or schooled-progress. Intersecting to working flow integration, Progress Governing means one shall has the free and be protected to use his rights in editing, especially his **editing of decision, epistemic and voting**, not locked from software, hardward or anything else.
* Capabilities IV -- Trust Information Transmit(**TIT**). A modern editor construct from his calculation, his visual structure and composition, his story from user and to user. Information both characterized or not-characterized, is the soul of **editor-user-story cycle**. A modern editor has the capabilities to **single out, management and delivery information** to and from his user, by graphical interface, the network, or a piece of paper.

![CE4-1](https://github.com/billyeatcookies/biscuit/assets/1416332/d5e76a97-68a5-4f53-bdf0-14e92d509754)

![CE4-2](https://github.com/billyeatcookies/biscuit/assets/1416332/3437d812-8072-4970-82ce-b34262b6335f)

And so, "category of extendsion" or "interconnect inside editor components" shall build on the stone of thus four capabilities. And as next step, it is possible that be a document on how this four implemented in Biscuit.

**Comment by billyeatcookies** [comment]
Hey @ltaoist, thanks for the good notes!

From my understanding, you are suggesting a more intentional and structured development process that aligns with these capabilities. By focusing on these capabilities, I believe that the resulting editor will be more robust, flexible, and user-friendly, encompassing a range of functionalities that address content manipulation, responsiveness, workflow integration, and information management.

In essence, we will be able to establish a conceptual framework that informs the design and development decisions for the Biscuit project, ensuring that future extensions and internal components align with these identified capabilities for a more coherent and powerful editor.

I have taken good notes from your suggestions, I will be updating the code as well to be more readable, more well documented! also take a look at the work-in-process documentation of biscuit: https://billyeatcookies.github.io/biscuit/

**Comment by ltaoist** [comment]
I think your highlights is outstanding. Yes, I am try to suggest a more intentional and structured development process. And more, robust, flexible, and user-friendly, functionalities ... will be attractive.

In the other hand, I am afraid should a more structured design of the editor, but what you comment that "a more intentional and structured development process", I think may not cost too much, and, will be good enough. And so on, a framework might be infeasible, but a "conceptual" framework will work.

I am amazing of your wisdom. You point things in a right way much more that me at least in my view!

======================

Sorry for my verbose. I don't know how to proposal this in short.

As practice, recent day I try to reconstruction libreoffice for several steps. In first step, we want build it by another build system, yes "monkey2". Now we have discover some issue. Firstly is that the well famous “conditional compile” or “conditional build” might divide into "feature optional building", "platform specific building", and "language level conditional building". Now I have to prepare for a serious modification in the tons line of the libreoffice source. **If I choice to advance this works in biscuit, how should I construct a user interface? (as I am the only user may be now.) Typically it might be a pop window for building message. There are two options: ① try to allocate a new window as text base interface, ② a more interesting or innovative way. Can I get any help from you? I can try to implement an idea, but I can find a an attractive mechanism.**

**An attractive mechanism not a framework.**
**An attractive mechanism not a framework.**
**An attractive mechanism not a framework.**

While I say mechanism, or a conceptual framework, I actually refer to a question -- "**_How should computation fly?_**" Actually I think apple work well. Some example:

<https://developer.apple.com/design/human-interface-guidelines/designing-for-visionos>
<https://developer.apple.com/design/human-interface-guidelines/immersive-experiences>

On the opposite side, google do bad. Some example:

<https://developer.android.com/topic/architecture>

As a member in programmer's programming helper stack, I think editor will help programmer to construct the program, the software, the computation, so give power to computation flying is important and apple works well. But google just trap developer into their "framework", "architecture".

======================

All and all, my conclusion is that it well better be for some **graph** about how things work together. And, I might try to integrate with the build system more deeply.

Good Luck!

**Comment by billyeatcookies** [comment]
@ltaoist the idea is quite amazing, sorry for the delay (due to my uni). I will document the whole thing gradually, see the progress so far at https://billyeatcookies.github.io/biscuit

**Comment by ltaoist** [comment]
Dear Lord Billy, Sorry for I lost a long time. However after such a long time separation, I finally found what here has done is just really good. And I have something new.

I think document now is accommodated. Good jobs!

I think the class name is hard, this is some root of the difficult for further stepping. I started to do some analyse and prepare for a new commit.

**Comment by billyeatcookies** [comment]
@ltaoist haha thanks for the review! ❤️ I will try to work on the docs further

**Comment by ltaoist** [comment]
After a new structure for core packages, I think some analyse would be more; for how to establish functions and creativity part more simply.

**Comment by ltaoist** [comment]
For more, go <https://github.com/billyeatcookies/biscuit/discussions/218>
