### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by billyeatcookies** [billyeatcookies/Biscuit#19]
The editor is currently not supporting linux operating system. 
## Bugs
Bugs identified so far.
- keysym ```<Control-`>``` doesn't work 
- `cmd` is not recognized in linux
- `tk-extrafont` library have trouble installing in linux

Fixes:
- [x] #21
  A class to hold all needed data of the working machine. This shall include operating system, version, python version, etc.
- [ ] Configure new keysym to replace ```<Control-`>``` when on linux.
- [ ] instead of `cmd` use `bash` in linux (make choice based on `platform.system()`)
- [ ] add fixes to avoid the error while installing `tk-extrafont` in linux

**Comment by cid0rz** [comment]
nice! I will continue investigating. Didnt want to open the issue myself, so thanks :)
