### ISSUE TITLE
Use pseudoterminals (PTY) instead of pipes for terminal emulation

### ISSUE THREAD

**Issue by tigran2008** [billyeatcookies/biscuit#204]
Consider using pseudoterminals instead of `subprocess.PIPE` for implementing the terminal emulation functionality. Unlike pipes, pseudoterminals allow to truly emulate the behavior of a terminal, such as letting programs see the dimensions of the terminal, among other features.

I have stumbled upon the [yawinpty](https://pypi.org/project/yawinpty/) (for Windows) and [ptyprocess](https://pypi.org/project/ptyprocess/) (for POSIX-like platforms, i.e., Linux, macOS, and the like) libraries for achieving this. They also don't require you to set up a separate thread―they simply have read/write methods.

Unfortunately, yawinpty and ptyprocess are very different by design from each other. However, I believe that it shouldn't be too difficult to implement an abstraction layer for them.

**Comment by billyeatcookies** [comment]
Great suggestion! there are many limitations to the current way biscuit's integrated terminals are set up, so I just left it at a works-dont-touch state xd but yea this is the right way to do it, huge thanks for also sharing the packages :)

**Comment by billyeatcookies** [comment]
since **yawinpty** is deprecated, using [**pywinpty**](https://github.com/andfoy/pywinpty)
