### ISSUE TITLE
Crediting Porcupine

### ISSUE THREAD

**Issue by Akuli** [billyeatcookies/biscuit#216]
## Bug

The language server code is very clearly based on Porcupine. I think it's great that you found my code useful, and I'm totally fine with you using my code, but IMO it would be fair to credit me in some way instead of making it look like you wrote everything by yourself from scratch :)

For example, [file biscuit/core/components/lsp/utils.py in commit 3191e44e6](https://github.com/billyeatcookies/biscuit/commit/914da9f9d0b1848ae07838bb20618cdfc22c846f#diff-3191e44e695813d2ed2a65838cc9fa675515ae484febcedf9d9e109188fb7095) contains nothing but code copy/pasted from [porcupine's langserver plugin](https://github.com/Akuli/porcupine/blob/859404d86de2f0521ddd4dfdfb52bfcd0fdfa9fe/porcupine/plugins/langserver.py). But if I search for my name or Porcupine, I don't find anything in the repo.

I think it would be fair (and required by my MIT license) to mention me or Porcupine in some way. For example, you could add a one-line comment like

```
# This code is based on Porcupine's LSP plugin https://github.com/Akuli/porcupine/
```

to the relevant files. Or if you want to strictly comply with my MIT license (I don't really care), put this somewhere, maybe along with some short explanation:

```
Copyright (c) 2017-2023 Akuli
```

### System Information
(not relevant)

**Comment by billyeatcookies** [comment]
@Akuli first of all, sorry for not crediting porcupine properly. I got to know about sansio-lsp-client and porcupine through rdbende. After going through the client I thought its really neat, but still had some doubts on the implementation and the LSP is a topic I've not touched before, and there weren't much resources on writing a client like this, so I did refer to the client written for porcupine for writing biscuit's and that helped alot ❤️ I will make changes to add in the credits to acknowledge the project

**Comment by billyeatcookies** [comment]
@Akuli I've copied the license along with the copyright to the lsp client implementation, and have also mentioned the license in source files too, let me know if that's fine :)

**Comment by Akuli** [comment]
This is awesome! Thanks!
