### ISSUE TITLE
Cannot open empty files

### ISSUE THREAD

**Issue by vyshnav-vinod** [billyeatcookies/biscuit#250]
## Bug
> Describe the bug

Whenever a user creates a empty file within the editor and opens it, it shows `"This file is not displayed in this editor because it is either binary or uses an unsupported text encoding."` I thought it might be a bug of the editor and when i made an empty file outside and then opened it in the editor it still shows the error. I encountered this while checking #41 

### System Information
- OS: Ubuntu 22.04
- Python Version: 3.10.12

**Comment by vyshnav-vinod** [comment]
I guess i found a simple fix for this
We just have to return 'utf-8' if `bomstring` is empty

[bomstring](https://github.com/billyeatcookies/biscuit/blob/a400c9ecf12f861b40f38b5a094826228c251bdf/biscuit/core/components/editors/texteditor/text.py#L603)

I can open a PR but i guess this might be a simple fix. Also this assumes that every empty file will be of 'utf-8' encoding so if you prefer something else you can change that

**Comment by billyeatcookies** [comment]
@vyshnav-vinod exactly, the problem is caused by bom check while reading an existing file. case where the file is empty is not handled, and code tries to access non existent data. And yes, we can default the encoding to utf-8, sounds good :)
