### ISSUE TITLE
Tetris doesn't work

### ISSUE THREAD

**Issue by rohankishore** [billyeatcookies/Biscuit#61]
## Bug
> When i click "play tetris" from the palette, Snake is being played instead of Tetris (my english sucks ik sorry)

### System Information
- OS: Cumulative Update for Windows 11 Insider Preview (10.0.22631.1972) (KB5027295)
- Python Version: 3.11.4
- CPU : Ryzen 5 5600H

**Comment by billyeatcookies** [comment]
@rohankishore this issue was regarding a closure problem, has been resolved in https://github.com/billyeatcookies/Biscuit/commit/bc1805228eec4fda9cfb5d902617e180fbe1376d. 

Try doing a `git pull` in local branch and let me know again if the problem is still there! ❤

**Comment by rohankishore** [comment]
Ok its working now... Thanks
