### ISSUE TITLE
Errors when loading Biscuit

### ISSUE THREAD

**Issue by Moosems** [billyeatcookies/biscuit#86]
When I try to load Biscuit I get the following:
 - ImportError: cannot import name 'windll' from 'ctypes'
 - ModuleNotFoundError: No module named 'hintedtext' (after commenting both imports of windll (I would recommend using isort on the project ;) )).
 - ModuleNotFoundError: No module named 'filetype' ( After removing the hintedtext)
 - ModuleNotFoundError: No module named 'tkextrafont'
 - ModuleNotFoundError: No module named 'tksvg' (tksvg has actually been having issues downloading for a while and there is a PR looking to fix the module)
 - NameError: name 'git' is not defined
 - Error shows that git isn't installed even though I use it almost every day XD
 - Probably many more I can't get to yet.

### System Information
- OS: MacOS
- Python Version: 3.11

**Comment by billyeatcookies** [comment]
Aha! mac OS support, that I have no idea of since I'm on windows xd I would love to get some instructions from you on fixing this up, if possible ❤ so far I have been maintaining the windows support, and @cid0rz looks out for linux compatibility.

also the ModuleNotFoundErrors seems like they are not installed at all, or maybe the case is that those libs are not supported in mac, though I highly doubt that's the case. the filetype, gitpython modules should be cross platform supported. 

can you try reinstalling all the requirements `pip install -r requirements.txt` or using poetry if you don't want your packages bloated xd simply [`poetry install`](https://python-poetry.org/)

**Comment by Moosems** [comment]
I installed from requirements.txt twice before running it 😅. I tried searching for many of them individually and pip returned package not found errors.

**Comment by billyeatcookies** [comment]
okay that sorted imports a bit too much xd 
![image](https://github.com/billyeatcookies/Biscuit/assets/70792552/3dd0fc34-21e1-41f7-afef-0d2e1b170ba4)

**Comment by Moosems** [comment]
> okay that sorted imports a bit too much xd 
> 
> ![image](https://github.com/billyeatcookies/Biscuit/assets/70792552/3dd0fc34-21e1-41f7-afef-0d2e1b170ba4)
> 
> 

That's hilarious 🤣.

**Comment by Moosems** [comment]
Any progress on Mac support?

**Comment by Moosems** [comment]
What is tkextrafont doing exactly?

**Comment by Moosems** [comment]
I found a workaround to install fonts on the users system instead of having to rely on font libraries to import them into the tcl runtime in a personal project of mine.

**Comment by Moosems** [comment]
```
**    # Install the Fira Code font
    font: TTFont = TTFont(static_folder / "FiraCode-VariableFont_wght.ttf")
    # Font directories:
    # MacOS: "/Library/Fonts/",
    # Windows: "C:\Windows\Fonts",
    # Linux: "~/.fonts"
    if SYSTEM == "Darwin":
        font_dir = Path("/Library/Fonts")
    elif SYSTEM == "Windows":
        font_dir = Path("C:/Windows/Fonts")
    else:
        font_dir = Path("~/.fonts").expanduser()

    font_dir.mkdir(parents=True, exist_ok=True)
    font.save(font_dir / "FiraCode-VariableFont_wght.ttf")
```

**Comment by Moosems** [comment]
I'd just ditch it :).

**Comment by billyeatcookies** [comment]
@Moosems I tried this method but it seems i can never bypass the protection windows have
```
  File "D:\test.py", line 14, in <module>
    font.save(font_dir / "test.ttf")
    with open(file, "wb") as file:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Windows\\Fonts\\test.ttf'
```

**Comment by Moosems** [comment]
Oof 😕. That's not great.

**Comment by Moosems** [comment]
You can't change directory permissions from os calls?

**Comment by rdbende** [comment]
> You can't change directory permissions from os calls?

If you don't have the permission to access it, you probably can't modify its permission either.

**Comment by billyeatcookies** [comment]
@Moosems yep rdbende's right, I will have to launch the program in administrator mode in order to do this. Maybe I can make this possible by building an installer program that requires administrator permissions, and during the installation of app, I can also install the fonts. I dont't see another way to bypass windows protection other than this.

**Comment by Moosems** [comment]
I think that's the best way to be honest 😕.

**Comment by rdbende** [comment]
Windows doesn't have a per-user fonts directory? That's pretty lame tbh.

**Comment by rdbende** [comment]
Actually, I think tukaan has some repo somewhere to build `tkextrafont` for macOS.

**Comment by rdbende** [comment]
Yeah, https://github.com/tukaan/Serif (though I made some improvements to it, and also renamed it to `libserif`)
It doesn't have build actions, but it's pretty simple: you just need to run the Makefile, and get upload the action deployments. If you want automatic Linux builds as well, you will need to run `sudo apt install tcl-dev tk-dev` first.

**Comment by billyeatcookies** [comment]
> Windows doesn't have a per-user fonts directory? That's pretty lame tbh.

@rdbende actually fonts can be installed for user only in windows, 

![image](https://github.com/billyeatcookies/Biscuit/assets/70792552/29e0b217-52ec-4e86-bc26-17030b0f1063)

and these are stored at

![image](https://github.com/billyeatcookies/Biscuit/assets/70792552/07705732-7146-496a-968b-d37345fe3572)

but, manually copying the ttf files to that directory won't do though, will have to go through the installation processes.

**Comment by tigran2008** [comment]
I think the viable solution here, if possible of course, would be making a Tcl package which lets one use fonts in Tk without actually installing them on the system, and then creating a Python wrapper for that package. Something similar to [this (Eliav2/tkinterdnd2)](https://github.com/Eliav2/tkinterdnd2)

I don't know Tcl, though, so unfortunately I cannot give a helping hand.

**Comment by Moosems** [comment]
That's the idea of tkextrafont @tigran2008 but it's unmaintained.

**Comment by billyeatcookies** [comment]
closing as #164 mentions this problem
