### ISSUE TITLE
Maximizing window gives error in linux

### ISSUE THREAD

**Issue by billyeatcookies** [billyeatcookies/Biscuit#91]
## Bug
Maximizing window gives error in linux.
```
File "/home/cid0rz/.pyenv/versions/3.11.4/lib/python3.11/tkinter/init.py", line 2276, in wm_state
    return self.tk.call('wm', 'state', self._w, newstate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bad argument "zoomed": must be normal, iconic, or withdrawn
```

### System Information
- OS: arch linux
- Python Version: 3.11

**Comment by littlewhitecloud** [comment]
> 
Try this?
```python
self.attributes("-fullscreen", True)
```

**Comment by rdbende** [comment]
> Try this?

`self.attributes("-fullscreen", True)`

LOL, that makes the window full screen :D

No, this is how to maximize a Tk window on Linux: 

```python
w.wm_attributes("-zoomed", True)
```

**Comment by billyeatcookies** [comment]
Actually current solution of maximize uses `-zoomed`! but apparently it fails on arch linux for some reason (blame @cid0rz's PC)
```
_tkinter.TclError: bad argument "zoomed": must be normal, iconic, or withdrawn
```

https://github.com/billyeatcookies/Biscuit/blob/bf7ef4acc9d4417c6ec04cec276849c2a3cee7e4/biscuit/core/utils/events.py#L59-L61
