### ISSUE TITLE
Stacking order and other Window issues in Linux (Wayland + GNOME)

### ISSUE THREAD

**Issue by billyeatcookies** [billyeatcookies/Biscuit#95]
## Bug
Custom titlebar doesn't really work well on Linux. Because of `.wm_overrideredirect()` it stays always on top, and the filedialog goes behind the window. Resizing doesn't work, and any of the menus either. The menus open, but as soon as mouse is moved, they disappear, and selecting items with the keyboard doesn't work either.

_Originally posted by @rdbende in https://github.com/billyeatcookies/Biscuit/issues/84#issuecomment-1656018455_

### System Information
- OS: Wayland + GNOME, using Mutter WM
- Python Version:  3.11

**Comment by billyeatcookies** [comment]
@cid0rz @rdbende could you confirm the stacking order issue has been fixed, i have made the `overrideredirect` windows specific, this was the only workaround so far

**Comment by rdbende** [comment]
Stacking order works. The double titlebar and window border looks a bit weird, but that's a minor thing. Biscuit couldn't open any file correctly for some reason (even though they are UTF-8 text files)

![image](https://github.com/billyeatcookies/Biscuit/assets/77941087/58c9f745-9b48-4c63-978b-0a5b935179fd)

**Comment by billyeatcookies** [comment]
@rdbende thanks alot! ❤ and the two titlebar issuem I'm still unsure of how to add the menus as part of gnome titlebar, but nothing is impossible only to figure it out at a point! I will look into gtk docs, let me know if you have something on that!

I'm not able to reproduce the unsupported files yet, It should be a system specific issue, the statusbar was also supposed to update on file open if file is supported, also i can see that text wrap is not turned off by default on linux and the highlightborder that is not supposed to be there too!

https://github.com/billyeatcookies/Biscuit/blob/6f3a62ef7814a192ac4d1132b369939e97fb510a/biscuit/core/components/editors/texteditor/text.py#L307-L318
